import { router, json, error, ai, db, storage, requireAuth } from '@appdeploy/sdk';
import { secrets } from '@appdeploy/sdk';

type StoredMessage = { role: 'user' | 'assistant'; content: string; imageUrl?: string; fileName?: string };
type ChatRecord = { ownerUserId: string; clientId: string; title: string; messages: StoredMessage[]; updatedAt: number };
function safeName(name: string) { return name.replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 120) || 'file'; }
export const handler = router({
  'GET /api/_healthcheck': [async () => json({ message: 'Success', features: ['chat', 'image', 'research', 'agent', 'cloud-history', 'file-storage', 'owner-manager'] })],
  'POST /api/chat': [async ({ body }) => { const input = body as { message?: string; history?: StoredMessage[]; image?: { data: string; mimeType: string }; fileText?: string; thinkingMode?: 'FAST' | 'DEEP' }; const message = input.message?.trim() || 'Analyze the attached content.'; try { const context = input.fileText ? `\nAttached file content:\n${input.fileText.slice(0, 40000)}` : ''; const result = await ai.generate({ system: 'You are romsuperior ai, an advanced general-purpose assistant. Be accurate, explain reasoning when useful without exposing private chain-of-thought, and clearly state uncertainty. You can help with writing, coding, planning, analysis, math, research, and multimodal tasks.', messages: [...(input.history || []).slice(-14), { role: 'user', content: message + context }], images: input.image ? [input.image] : undefined, thinkingMode: input.thinkingMode === 'DEEP' ? 'DEEP' : 'FAST', maxTokens: 2200 }); return json({ reply: result.text }); } catch (err) { console.error('AI generation failed', err); return error('AI service temporarily unavailable', 503); } }],
  'POST /api/agent': [async ({ body }) => { const input = body as { message?: string; history?: StoredMessage[]; thinkingMode?: 'FAST' | 'DEEP' }; const task = input.message?.trim(); if (!task) return error('Agent task is required', 400); try { const result = await ai.run({ system: 'You are romsuperior ai Agent. Complete the user task using bounded tool calls. Use browse_url only when a web page is needed. Never invent web contents. Summarize tool findings and produce a useful final answer. Do not expose hidden chain-of-thought.', messages: [...(input.history || []).slice(-10), { role: 'user', content: task }], tools: [{ name: 'browse_url', description: 'Fetch and read a public web page at a supplied http or https URL.', parameters: { type: 'object', properties: { url: { type: 'string' } }, required: ['url'] } }], maxSteps: 4, maxTokens: 2200, thinkingMode: input.thinkingMode === 'DEEP' ? 'DEEP' : 'FAST', onToolCall: async (name, args) => { if (name !== 'browse_url') return { error: 'Unknown tool' }; const url = String(args.url || '').trim(); if (!/^https?:\/\//i.test(url)) return { error: 'Only http and https URLs are allowed.' }; const page = await ai.scrape({ url }); return { title: page.title || url, status: page.status, text: page.text.slice(0, 18000) }; } }); return json({ reply: result.text, steps: result.steps }); } catch (err) { console.error('Agent failed', err); return error('Agent task temporarily unavailable', 503); } }],
  'POST /api/image': [async ({ body }) => { const input = body as { prompt?: string }; if (!input.prompt?.trim()) return error('Prompt is required', 400); try { const result = await ai.imageGen({ prompt: input.prompt.trim() }); return json({ image: result.image.data, mimeType: result.image.mimeType }); } catch (err) { console.error('Image generation failed', err); return error('Image generation temporarily unavailable', 503); } }],
  'POST /api/research': [async ({ body }) => { const input = body as { url?: string; thinkingMode?: 'FAST' | 'DEEP' }; const url = input.url?.trim(); if (!url || !/^https?:\/\//i.test(url)) return error('Enter a valid http or https URL', 400); try { const page = await ai.scrape({ url }); if (page.status >= 400) return error('Could not read that web page', 502); const result = await ai.generate({ system: 'Summarize the supplied web page faithfully. Identify the main points and clearly separate facts from uncertainty. Do not invent details.', prompt: page.text.slice(0, 40000), maxTokens: 1800, thinkingMode: input.thinkingMode === 'DEEP' ? 'DEEP' : 'FAST' }); return json({ title: page.title || url, summary: result.text }); } catch (err) { console.error('Research failed', err); return error('Research service temporarily unavailable', 503); } }],
  'GET /api/manager/overview': [async ({ event }) => { const configuredOwner = await secrets.readSecret('OWNER_EMAIL').catch(() => ''); const headers = event.headers || {}; const suppliedOwner = headers['x-manager-owner'] || headers['X-Manager-Owner'] || ''; if (!configuredOwner || suppliedOwner !== configuredOwner) return error('Unauthorized', 401); const result = await db.list<ChatRecord>('chats', { limit: 50 }); const chats = result.items.sort((a, b) => b.updatedAt - a.updatedAt); const users = new Set(chats.map(chat => chat.ownerUserId)); const messages = chats.reduce((sum, chat) => sum + chat.messages.length, 0); return json({ stats: { chats: chats.length, users: users.size, messages }, recentChats: chats.slice(0, 10).map(chat => ({ title: chat.title, updatedAt: chat.updatedAt, messages: chat.messages.length })) }); }],
  'GET /api/chats': [requireAuth(), async ({ user }) => { const ownerUserId = user!.userId; const result = await db.list<ChatRecord>('chats', { filter: { ownerUserId }, limit: 50 }); const chats = result.items.sort((a, b) => b.updatedAt - a.updatedAt).map(item => ({ id: item.clientId, title: item.title, messages: item.messages, updatedAt: item.updatedAt })); return json({ chats }); }],
  'POST /api/chats': [requireAuth(), async ({ body, user }) => { const input = body as { id?: string; title?: string; messages?: StoredMessage[] }; if (!input.id || !input.title || !Array.isArray(input.messages)) return error('Chat id, title and messages are required', 400); const ownerUserId = user!.userId; const record: ChatRecord = { ownerUserId, clientId: input.id, title: input.title.slice(0, 120), messages: input.messages.slice(-100), updatedAt: Date.now() }; const existing = await db.list<ChatRecord>('chats', { filter: { ownerUserId, clientId: input.id }, limit: 5 }); if (existing.items[0]) { const [ok] = await db.update('chats', [{ id: existing.items[0].id, record }]); if (!ok) return error('Could not update chat', 500); return json({ saved: true, id: input.id }); } const [id] = await db.add('chats', [record]); if (!id) return error('Could not save chat', 500); return json({ saved: true, id: input.id }); }],
  'DELETE /api/chats/:id': [requireAuth(), async ({ params, user }) => { const ownerUserId = user!.userId; const clientId = params.id; const existing = await db.list<ChatRecord>('chats', { filter: { ownerUserId, clientId }, limit: 5 }); if (!existing.items[0]) return json({ deleted: false }); const [ok] = await db.delete('chats', [existing.items[0].id]); return json({ deleted: Boolean(ok) }); }],
  'POST /api/files': [requireAuth(), async ({ body, user }) => { const input = body as { name?: string; content?: string; contentType?: string }; if (!input.name || !input.content) return error('File name and content are required', 400); if (input.content.length > 8000000) return error('File is too large', 413); const path = `users/${user!.userId}/${Date.now()}-${safeName(input.name)}`; const [ok] = await storage.write([{ path, content: input.content, contentType: input.contentType || 'application/octet-stream' }]); if (!ok) return error('File storage failed', 500); const [{ url }] = await storage.url([path]); return json({ stored: true, name: input.name, path, url }); }]
});
